### PR TITLE
Updates for new client_golang

### PR DESCRIPTION
**Pull request by beorn7**

### CODE REVIEW

**Comment by beorn7** [comment]
My feeble attempts to fix CircleCI don't seem to have helped. memcached seems unreachable... Any hints?

**Comment by grobie** [comment]
There was an alternative attempt in https://github.com/prometheus/memcached_exporter/pull/30/files.

@simonpasquier You've worked on the CircleCI upgrade in the past, any idea how we could fix the dependency?

**Comment by simonpasquier** [comment]
Hmm, looking at the CircleCI documentation it seems that the solution is to run the memcached container as a seconday container. I've tested with #32 and it does the trick.

**Comment by grobie** [comment]
Awesome! @beorn7 please remove your last commit.

**Comment by beorn7** [comment]
Removed last commit and rebased on top of master.

**Comment by beorn7** [comment]
\o/

**Pull request merged**
