### PR TITLE
Refactor exporter so that it can be used as a library.

### PR DESCRIPTION
**Pull request by tamalsaha**
We are using the Memcached exported in our project as a library. This pr refactors the exporter to a `collector` subpackage so that it can be used as a library.

### CODE REVIEW

**Comment by brian-brazil** [comment]
You've submitted two of these PRs now, may I ask why you are using this as a library?

**Comment by tamalsaha** [comment]
We are using this in our Kubernetes controllers. We options are coming from a Kubernetes CRD and http handlers are registered. So, we are using the exporter as a library.

**Comment by brian-brazil** [comment]
Your Kuberentes controllers contain a memcached and a haproxy inside their binary?

**Comment by tamalsaha** [comment]
Yes. It runs as a side car to a Memcache/HAproxy.

Memcached:https://github.com/kubedb/operator/blob/master/cmds/exporter_handler.go#L212
HAProxy: https://github.com/appscode/voyager/blob/master/pkg/cmds/exporter.go#L140

**Comment by brian-brazil** [comment]
I think you should read https://www.robustperception.io/one-agent-to-rule-them-all/

**Comment by tamalsaha** [comment]
I read that. Can you please point to what I am missing?

**Comment by brian-brazil** [comment]
You're creating an uberagent, which is not recommended.

**Comment by tamalsaha** [comment]
We are not using it like a uber agent . Each memcache / HAProxy pod gets its own sidecar exporter. We need some extra glue code to deal with Kubernetes api and its dynamic nature (example, connect credentials change, etc). So, we have decided to write our own `command` that adds those glue code and uses the exporters as a library. I hope this is cleared up now.

**Comment by brian-brazil** [comment]
You shouldn't have to care about the dynamic nature of things if you are already using exporters as a sidecar, and I don't see anything dynamic in your code.

**Comment by tamalsaha** [comment]
> You shouldn't have to care about the dynamic nature of things if you are already using exporters as a sidecar.

Are you saying that side cars will restart when configuration change (say credential changes)? We try not to restart pods unless it has to. We find `soft-loading` leads to better ux. That is a application level decision we have made.

> I don't see anything dynamic in your code.

That is something we are working towards. https://github.com/appscode/voyager/issues/212

This pr follows the pattern in other exporters : example: https://github.com/prometheus/mysqld_exporter .

**Comment by brian-brazil** [comment]
> Are you saying that side cars will restart when configuration change (say credential changes)?

If that's what's needed. That's a pretty normal thing to do, and credential changes are also quite rare.

> We find soft-loading leads to better ux.

This is all infrastructure, user experience doesn't really come in to it.

> example: https://github.com/prometheus/mysqld_exporter .

The MySQL exporter is this way for an entirely unrelated reason.

**Comment by tamalsaha** [comment]
> If that's what's needed. That's a pretty normal thing to do, and credential changes are also quite rare.

Updating credentials is rare and this is why we have not addressed this issue so far. Rather left it as a note for users. But we want to fix that now, given other high priority issues has been resolved.

> This is all infrastructure, user experience doesn't really come in to it.

Not really, Everytime HAProxy restarts, it can be noticeable effect on http connections, etc. Yes, there are ways to configure things that HA is not affected. But some people don't set thing up that way and we don't want to force them.

Frankly I rather get an answer on this pr without discussing various design decisions on my application side.

**Comment by brian-brazil** [comment]
Looking a bit closer at your code what you have written is a blackbox-style exporter due the podIP URL parameter. Aside from not being the way exporters are intended to be used, this may also allow secrets to be extracted, see https://prometheus.io/docs/operating/security/#exporters

> Not really, Everytime HAProxy restarts, it can be noticeable effect on http connections, etc.

That's certainly true for HAProxy, but it's not true for exporters as user traffic does not go through them.

> Frankly I rather get an answer on this pr without discussing various design decisions on my application side.

We get lots of requests for features and changes, many of which it is unclear if they make sense or why a user would want to do that. Most of the time it turns out that the user had misunderstood something and we can help them on the right path, but if not we still need to balance the increased code complexity and support overhead for us from a PR such as this against your use case.

What you're proposing here is also not just a code change, but would be in effect a new policy for the project as a whole that we should factor all our Go exporters in this slightly more complicated fashion. I personally would worry here about the support impact if we make it too easy to do things like this, as I'd expect most users wanting to take advantage of this would be doing so specifically to violate exporter guidelines.

As this affects the whole project, I think others should also weigh in.

**Pull request closed without merging**
