### PR TITLE
Switch to kingpin for flags

### PR DESCRIPTION
**Pull request by carlpett**
This PR switches to kingpin for flags, as per [prometheus #2455](https://github.com/prometheus/prometheus/issues/2455).

### CODE REVIEW

**Comment by grobie** [comment]
Hey @carlpett, I had to add a follow-up fix to adjust the vendoring of logrus and add a missing package: https://github.com/prometheus/memcached_exporter/commit/7ed897cb43803ea075f1521e99fb81ceb3405473

I'd suggest to check with `govendor status` and `govendor list` that all dependencies are correctly vendored.

**Comment by grobie** [comment]
The added package came probably from the newer logrus I added. Your change didn't touch logrus in the vendor file: https://github.com/carlpett/memcached_exporter/blob/0e257593c48ee88ff12d105ac4d6dd6cacd037a6/vendor/vendor.json#L5-L10

I assume this is an issue of your filesystem being case insensitive?

**Comment by carlpett** [comment]
Probably. Still weird - it has shown up in other exporters. But never mind, you fixed it. Thanks for that! 
I'll make sure to check the vendor file from now on, rather than trust the output of `govendor status`.

**Comment by grobie** [comment]
Don't worry at all. Thanks so much for your contributions!

**Pull request merged**
