### PR TITLE
Move exporter logic to dedicated package

### PR DESCRIPTION
**Pull request by rfratto**
We want to embed memcached_exporter in the [Grafana Cloud Agent](https://github.com/grafana/agent), which requires the `Exporter` logic to be placed in a non-`main` package. 

Signed-off-by: Robert Fratto <robertfratto@gmail.com>

### CODE REVIEW

**Review by roidelapluie — APPROVED** [review]

**Comment by SuperQ** [comment]
Should we follow the `collector` package pattern that we use in other places like the node_exporter?

**Comment by rfratto** [comment]
Happy to change anything, and being consistent with node_exporter makes sense. Just so I understand, are you only referring to the package name or the [system to aggregate metrics from multiple mini-collectors](https://github.com/prometheus/node_exporter/blob/f645d4924224f1f3abab7b20798ca8e24957724c/collector/collector.go#L139)?

**Comment by grobie** [comment]
The node exporter is very special being an uber exporter for many different
kinds of metrics. I'm not sure what we'd gain by copying that pattern
around?

I'm in general find with this refactoring, sorry for the lack of response.
What do you think about following the common go repository structure with
cmd/ and pkg/ folders?

**Comment by rfratto** [comment]
`cmd/` makes a lot of sense, though not sure about whether `pkg/` fits here. I gave a quick scan through the projects under the GitHub org, and not all non-main packages are stored in the `pkg` subdirectory. I'm not sure I fully understand where to draw the line, though it seems to me that it is reserved for utility packages and not core functionality.

WDYT? I have no issues with moving it under `pkg/`, I'm personally a fan of that pattern.

**Comment by grobie** [comment]
I don't think the prometheus golang projects are the best examples for following common patterns. Several projects are older or very copy&pasted from such than the patterns which emerged in the go community over time.

I understand pkg/ to clearly signal "these packages are part of the public API of this project". The [golang-standards project](https://github.com/golang-standards/project-layout#pkg) describes it similarly:

> Library code that's ok to use by external applications (e.g., /pkg/mypubliclib). Other projects will import these libraries expecting them to work, so think twice before you put something here

I don't have a very strong feeling on this, but if the prometheus organization will generally start exposing exporter functionality packages, I'd hope following the standard project layout will help to understand the intentions.

**Comment by rfratto** [comment]
Thanks for the input, and sorry for the delay addressing the feedback here. I've moved the main package to `cmd/memcached_exporter` and the new `exporter` package to `pkg/exporter`.

**Comment by grobie** [comment]
Thanks a lot for your work and apologies for the late response. Looks great now!

**Review by grobie — APPROVED** [review]

**Pull request merged**
