### PR TITLE
Update Prometheus Go modules

### PR DESCRIPTION
**Pull request by SuperQ**
* Update Prometheus Go modules.
* Use new landing page.

### CODE REVIEW

**Comment by SuperQ** [comment]
CC @dannykopping

**Review by Nexucis — APPROVED** [review]

**Comment by dannykopping** [comment]
@SuperQ are you planning to cut a release any time soon?

**Comment by dannykopping** [comment]
@SuperQ sorry to pester you about this. We need this new metric in our prod environments as soon as possible.
I raised https://github.com/prometheus/memcached_exporter/pull/169 almost a month ago; is there a way I could help move things along?

**Comment by matthiasr** [comment]
I'll cut a release today!

**Comment by SuperQ** [comment]
Sorry, I had a release change half done, but forgot to push it.

https://github.com/prometheus/memcached_exporter/pull/172

**Pull request merged**
