### PR TITLE
Export `extstore_io_queue` gauge

### PR DESCRIPTION
**Pull request by dannykopping**
Also exported `extstore_pages_free` which seems to have been missed previously

### CODE REVIEW

**Comment by dannykopping** [comment]
@grobie just checking in: can you please review & merge this? It's currently blocking us

**Comment by dannykopping** [comment]
@SuperQ many thanks 👍 
How often do you folks cut patch releases?

**Comment by SuperQ** [comment]
Usually as needed / as we have time. This exporter is pretty simple and has few changes. Should be able to do one soon.

**Comment by dannykopping** [comment]
Great, thanks!

**Pull request merged**
